apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tomcatwas.fullname" . }}-config
  labels:
    {{- include "tomcatwas.labels" . | nindent 4 }}
  annotations:
    description: "ConfigMap for Tomcat WAS deployment"
    version: "1.0"
data:
  index.html: |
    <html><body><h1>Welcome to Tomcatwas</h1></body></html>
  mysql.jsp: |
    <%@ page import="java.sql.*" %>
    <html>
    <body>
      <h1>MySQL Connection</h1>
      <% 
        String url = "jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}";
        String username = "{{ .Values.database.user }}";
        String password = "{{ .Values.database.password }}";
        
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, username, password);
            String query = "SELECT * FROM member";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                out.println("Data: " + rs.getString("name") + "<br>");
            }
        } catch (Exception ex) {
            out.println("Error: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                out.println("Error closing resources: " + e.getMessage());
            }
        }
      %>
    </body>
    </html>
  main.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tennis Market</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 20px;
            }
            h1 {
                font-size: 2em;
            }
            .product-container {
                display: flex;
                justify-content: center;
                gap: 20px;
                margin-top: 20px;
            }
            .product {
                text-align: center;
            }
            .product img {
                width: 100px;
                height: 100px;
            }
            .order-button {
                display: block;
                margin-top: 10px;
                padding: 5px 10px;
                font-size: 1em;
            }
            .order-list-link {
                color: purple;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <h1>Tennis Market</h1>
        <p>Welcome to Tennis Market!<br>Enjoy your shopping.</p>
        <p><a href="/orderlist.html" class="order-list-link">order list</a></p>
        
        <div class="product-container">
            <div class="product">
                <img src="/images/redRacket.png" alt="Red Racket">
                <p>Red Racket</p>
                <button class="order-button">order</button>
            </div>
            <div class="product">
                <img src="/images/blueRacket.png" alt="Blue Racket">
                <p>Blue Racket</p>
                <button class="order-button">order</button>
            </div>
            <div class="product">
                <img src="/images/blackRacket.png" alt="Black Racket">
                <p>Black Racket</p>
                <button class="order-button">order</button>
            </div>
        </div>
    </body>
    </html>
