apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tomcatwas.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "{{ .Release.Name }}.example.com"  # Use your domain here
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tomcatwas.fullname" . }}
                port:
                  number: 8080
