apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tomcatwas.fullname" . }}-db-credentials
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-user: {{ .Values.database.user | b64enc | quote }}
