apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcatwas.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "tomcatwas.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
