apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginxweb.fullname" . }}-config
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
  annotations:
    description: "ConfigMap for NGINX web deployment"
    version: "1.0"
data:
  nginx.conf: |
    {{ .Values.nginx.config.nginxConf | indent 4 }}
  default.conf: |
    {{ .Values.nginx.config.defaultConf | indent 4 }}
