apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginxweb.fullname" . }}
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginxweb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginxweb.name" . }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-storage
              mountPath: /mnt/data
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginxweb.fullname" . }}-config
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
