apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginxweb.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginxweb.fullname" . }}
                port:
                  number: 80
