apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginxweb.fullname" . }}
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "nginxweb.name" . }}
  type: {{ .Values.service.type }}
