apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mysqldb.fullname" . }}
  labels:
    {{- include "mysqldb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mysqldb.fullname" . }}
                port:
                  number: 3306
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
