apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  rootPassword: {{ .Values.mysql.rootPassword | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
