apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysqldb.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "mysqldb.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: {{ .Values.service.type }}
