nginx:
  image: nginx:latest
  config:
    nginxConf: |
      events {}
      http {
          include       mime.types;
          default_type  application/octet-stream;
          include /etc/nginx/conf.d/*.conf;
      }
    defaultConf: |
      server {
          listen 80;
          server_name localhost;
          location / {
              proxy_pass http://tomcat-service.default.svc.cluster.local:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      }

service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "Internal"

secret:
  dbPassword: "supersecretpassword"

ingress:
  host: "example.com"
